---
- hosts: ssh-ca

  tasks:

    - name: install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ntp
        - uuid

    - name: create the sshca user
      user:
        name: sshca
        system: yes

    - name: create users
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment|default(omit) }}"
        groups: sshca
      with_items: "{{ ssh_ca_users }}"

    - name: provision authorized SSH keys for users
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1.key }}"
        comment: "{{ item.1.comment|default(omit) }}"
        state: "{{ item.1.state|default('present') }}"
      with_subelements:
        - "{{ ssh_ca_users }}"
        - ssh_keys

    - name: add the sshca group to the sudoers for the forced command
      copy:
        src: sudoers-sshca
        dest: /etc/sudoers.d/sshca
        mode: 0440

    - name: provision superuser SSH keys
      authorized_key:
        user: root
        key: "{{ item.key }}"
        state: "{{ item.state|default('present') }}"
        comment: "{{ item.comment|default('omit') }}"
      with_items: "{{ ssh_ca_superuser_authorized_keys }}"

    - name: install ssh-ca
      copy:
        src: ssh-ca
        dest: /usr/local/bin/ssh-ca
        owner: sshca
        group: sshca
        mode: 0750

    - name: configure ssh-ca
      template:
        src: ssh-ca.conf.j2
        dest: /etc/ssh-ca.conf

    - name: configure sshd
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
      notify: restart ssh

    - name: create the CA directory
      file:
        dest: /usr/local/lib/ssh-ca
        state: directory
        owner: sshca
        group: sshca
        mode: 0750

    - name: install CA secret keys
      copy:
        content: "{{ item.secret }}"
        dest: /usr/local/lib/ssh-ca/{{ item.name }}
        owner: sshca
        group: sshca
        mode: 0600
      with_items: "{{ ssh_ca_keypairs }}"
      no_log: True

    - name: install CA public keys
      copy:
        content: "{{ item.public }}"
        dest: /usr/local/lib/ssh-ca/{{ item.name }}.pub
        owner: sshca
        group: sshca
        mode: 0640
      with_items: "{{ ssh_ca_keypairs }}"
      no_log: True

    - name: create the log directory
      file:
        dest: /var/log/ssh-ca
        state: directory
        owner: sshca
        group: sshca
        mode: 0750

    - name: sign the host keys
      command: ssh-keygen -s "/usr/local/lib/ssh-ca/{{ ssh_ca_configuration.use_ca_key }}"
        -h
        -P ""
        -I "{{ ssh_ca_configuration.use_ca_key }}"
        -n "{{ ansible_fqdn }}"
        /etc/ssh/ssh_host_rsa_key.pub
      args:
        creates: /etc/ssh/ssh_host_rsa_key-cert.pub

  handlers:

    - name: restart ssh
      service:
        name: ssh
        state: restarted
