---
- hosts: ssh-ca

  tasks:

    - name: add the ssh-ca-users group to the sudoers for the forced command
      copy:
        src: sudoers-sshca
        dest: /etc/sudoers.d/sshca
        mode: 0440

    - name: create the ssh-ca-users group
      group:
        name: ssh-ca-users
        state: present

    - name: create users
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment|default(omit) }}"
        groups: ssh-ca-users
        state: "{{ item.state|default(omit) }}"
      with_items: "{{ ssh_ca_users }}"

    - name: provision authorized SSH keys for users
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1.key }}"
        state: "{{ item.1.state|default('present') }}"
      with_subelements:
        - "{{ ssh_ca_users }}"
        - ssh_keys
      when: item.0.state|default("present") == "present"

    - name: provision superuser SSH keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ item.1.key }}"
        state: "{% if item.0.state|default('present') == 'present' and item.0.superuser|default(False) and item.1.state|default('present') == 'present' %}present{% else %}absent{% endif %}"
      with_subelements:
        - "{{ ssh_ca_users }}"
        - ssh_keys
