#!/bin/bash
#
# ssh-ca

set -o errexit
. /etc/ssh-ca.conf

function log_debug() {
    echo "$(date "+%F %T") ${*}" >> /var/log/ssh-ca/debug.log
}

function sign_user_key() {
    mkdir -p /tmp/ssh-ca
    principals="${SSH_ORIGINAL_COMMAND#* }"
    pubkey="$(mktemp /tmp/ssh-ca/${USER}_XXXXX.pub)"
    cat > "${pubkey}"
    ca_key="/usr/local/lib/ssh-ca/${SSH_CA_KEY}"
    serial="$(date +%s)"
    validity="${SSH_CA_CERTIFICATE_VALIDITY}"
    if [ -n "${SSH_CA_CERTIFICATE_OPTIONS}" ]; then
        options="-O ${SSH_CA_CERTIFICATE_OPTIONS}"
    fi
    log_debug "-s ${SSH_CA_KEY} -I ${USER} ${options} -V ${validity} -n ${principals} -z ${serial}"
    log_debug "$(ssh-keygen \
        -P "" \
        -s /usr/local/lib/ssh-ca/"${SSH_CA_KEY}" \
        -I "${USER}" \
        ${options} \
        -V "${validity}" \
        -n "${principals}" \
        -z "${serial}" \
        "${pubkey}" 2>&1)"
    cat "${pubkey%.pub}-cert.pub"
    rm "${pubkey}"
    rm "${pubkey%.pub}-cert.pub"
}

function sign_host_key() {
    mkdir -p /tmp/ssh-ca
    principals="${SSH_ORIGINAL_COMMAND#* }"
    pubkey="$(mktemp /tmp/ssh-ca/${USER}_XXXXX.pub)"
    cat > "${pubkey}"
    ca_key="/usr/local/lib/ssh-ca/${SSH_CA_KEY}"
    validity="+365d"
    log_debug "-s ${SSH_CA_KEY} -h -I ${SSH_CA_KEY} -V ${validity} -n ${principals}"
    log_debug "$(ssh-keygen \
        -P "" \
        -s /usr/local/lib/ssh-ca/"${SSH_CA_KEY}" \
        -h \
        -I "${SSH_CA_KEY}" \
        -V "${validity}" \
        -n "${principals}" \
        "${pubkey}" 2>&1)"
    cat "${pubkey%.pub}-cert.pub"
    rm "${pubkey}"
    rm "${pubkey%.pub}-cert.pub"
}

subcommand=${SSH_ORIGINAL_COMMAND% *}
case "${subcommand}" in
    user)
        sign_user_key
        ;;
    host)
        sign_host_key
        ;;
    config)
        echo SSH_ORIGINAL_COMMAND=$SSH_ORIGINAL_COMMAND
        echo USER=$USER
        echo SSH_CA_KEY=$SSH_CA_KEY
        echo SSH_CA_CERTIFICATE_VALIDITY=$SSH_CA_CERTIFICATE_VALIDITY
        echo SSH_CA_CERTIFICATE_OPTIONS=$SSH_CA_CERTIFICATE_OPTIONS
        ;;
esac
